//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Configuration;
using System.Windows;

namespace Freedom.Client.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class WindowPositionSettings : global::System.Configuration.ApplicationSettingsBase {

        //private static WindowPositionSettings defaultInstance = ((WindowPositionSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new WindowPositionSettings())));

        //public static WindowPositionSettings Default {
        //    get {
        //        return defaultInstance;
        //    }
        //}

        internal WindowPositionSettings(string settingsKey)
            : base(settingsKey)
        {
        }

        [UserScopedSetting]
        [DefaultSettingValue("False")]
        public bool HasSettings
        {
            get { return (bool)this[nameof(HasSettings)]; }
            set { this[nameof(HasSettings)] = value; }
        }

        [UserScopedSetting]
        public double Left
        {
            get { return (double)this[nameof(Left)]; }
            set { this[nameof(Left)] = value; }
        }

        [UserScopedSetting]
        public double Top
        {
            get { return (double)this[nameof(Top)]; }
            set { this[nameof(Top)] = value; }
        }

        [UserScopedSetting]
        public double Width
        {
            get { return (double)this[nameof(Width)]; }
            set { this[nameof(Width)] = value; }
        }

        [UserScopedSetting]
        public double Height
        {
            get { return (double)this[nameof(Height)]; }
            set { this[nameof(Height)] = value; }
        }

        [UserScopedSetting]
        public WindowState WindowState
        {
            get { return (WindowState)this[nameof(WindowState)]; }
            set { this[nameof(WindowState)] = value; }
        }

        public Rect Rect
        {
            get { return new Rect(Left, Top, Width, Height); }
            set
            {
                Left = value.Left;
                Top = value.Top;
                Width = value.Width;
                Height = value.Height;
            }
        }

        public Size Size
        {
            get { return new Size(Width, Height); }
            set
            {
                Width = value.Width;
                Height = value.Height;
            }
        }
    }
}
