//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics;
using System.Globalization;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using Freedom.Domain.Infrastructure;
using Freedom.Domain.Services.Repository;
using Freedom.ComponentModel;

namespace Freedom.Domain.Model
{
	[DataContract(Namespace = Namespace)]
	[KnownType(typeof(AggregateRoot))]
	[KnownType(typeof(NotificationBase))]

	public abstract partial class EntityBase : Entity
	{
		[DataMember(EmitDefaultValue = false)]
		public Guid Id
		{
			get { return _id; }
			set
			{
				if (_id == value) return;
				_id = value;
				MarkAsChanged();
				OnPropertyChanged();
			}
		}
		private Guid _id = Guid.NewGuid();

		public virtual void Copy(Entity entity)
		{
			EntityBase source = entity as EntityBase;

			if (source == null)
				throw new ArgumentException("entity", "entity must be an instance of EntityBase.");

			Id = source._id;
		}
	}
}
