//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using Freedom.Annotations;

namespace Freedom.Domain.Model
{
	[DataContract(IsReference = true, Namespace = Namespace)]
	public partial class MailingAddress : ComplexBase
	{
		[DataMember(EmitDefaultValue = false)]
		public string Street
		{
			get { return _street; }
			set
			{
				if (_street != value)
				{
					_street = value;
					OnPropertyChanged();
				}
			}
		}
		private string _street;

		[DataMember(EmitDefaultValue = false)]
		public string PostalCode
		{
			get { return _postalCode; }
			set
			{
				if (_postalCode != value)
				{
					_postalCode = value;
					OnPropertyChanged();
				}
			}
		}
		private string _postalCode;

		[DataMember(EmitDefaultValue = false)]
		public string City
		{
			get { return _city; }
			set
			{
				if (_city != value)
				{
					_city = value;
					OnPropertyChanged();
				}
			}
		}
		private string _city;

		[DataMember(EmitDefaultValue = false)]
		public string Province
		{
			get { return _province; }
			set
			{
				if (_province != value)
				{
					_province = value;
					OnPropertyChanged();
				}
			}
		}
		private string _province;

		[DataMember(EmitDefaultValue = false)]
		public string Country
		{
			get { return _country; }
			set
			{
				if (_country != value)
				{
					_country = value;
					OnPropertyChanged();
				}
			}
		}
		private string _country;

	}
}
