//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace Freedom.Domain.Model
{
	[DataContract(Namespace = Entity.Namespace)]
	public enum NotificationClass : int
	{
		[EnumMember]
		Unknown = 0,

		[EnumMember]
		CommandAccepted = 1,

		[EnumMember]
		CommandRejected = 2,

		[EnumMember]
		CommandFailed = 3,

		[EnumMember]
		ChangeRequestAccepted = 4,

		[EnumMember]
		ChangeRequestRejected = 5,

		[EnumMember]
		Informational = 6,

		[EnumMember]
		Warning = 7,

	}
}

