//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace Freedom.Domain.Model
{
	[DataContract(Namespace = Entity.Namespace)]
	public enum NotificationState : int
	{
		[EnumMember]
		None = 0,

		[EnumMember]
		Successful = 1,

		[EnumMember]
		Failed = 2,

	}
}

