//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics;
using System.Globalization;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using Freedom.Domain.Infrastructure;
using Freedom.Domain.Services.Repository;
using Freedom.Collections;
using Freedom.ComponentModel;

namespace Freedom.Domain.Model
{
	[DataContract(Namespace = Namespace)]

	public abstract partial class NumberedRoot : AggregateRoot
	{
		[DataMember(EmitDefaultValue = false)]
		public string Number
		{
			get { return _number; }
			set
			{
				if (_number == value) return;
				_number = value;
				MarkAsChanged();
				OnPropertyChanged();
			}
		}
		private string _number;

		public override void Copy(Entity entity)
		{
			base.Copy(entity);

			NumberedRoot source = entity as NumberedRoot;

			if (source == null)
				throw new ArgumentException("entity", "entity must be an instance of NumberedRoot.");

			Number = source._number;
		}
	}
}
