//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace Freedom.Domain.Model
{
	[Flags]
	[DataContract(Namespace = Entity.Namespace)]
	public enum OrderStatus : int
	{
		[EnumMember]
		[Description("Open")]
		Open = 0x0,

		[EnumMember]
		[Description("Filled")]
		Filled = 0x1,

		[EnumMember]
		[Description("Expired")]
		Expired = 0x2,

		[EnumMember]
		[Description("Cancelled")]
		Cancelled = 0x4,

	}
}

