//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics;
using System.Globalization;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using Freedom.Domain.Infrastructure;
using Freedom.Domain.Services.Repository;
using Freedom.Collections;
using Freedom.ComponentModel;

namespace Freedom.Domain.Model
{
	[DataContract(Namespace = Namespace)]

	public partial class Permission : EntityBase
	{
		public override string EntityTypeName
		{
			get { return "Permission"; }
		}

		[DataMember(EmitDefaultValue = false)]
		public string Description
		{
			get { return _description; }
			set
			{
				if (_description == value) return;
				_description = value;
				MarkAsChanged();
				OnPropertyChanged();
			}
		}
		private string _description;

		[DataMember(EmitDefaultValue = false)]
		public Guid RoleId
		{
			get { return _roleId; }
			set
			{
				if (_roleId == value) return;
				_roleId = value;
				MarkAsChanged();
				OnPropertyChanged();
			}
		}
		private Guid _roleId;

		[DataMember(EmitDefaultValue = false)]
		public virtual Role Role
		{
			get { return _role; }
			set
			{
				if (object.ReferenceEquals(_role, value)) return;

				_role = value;

				if (value != null)
					RoleId = value.Id;

				OnPropertyChanged();
			}
		}
		private Role _role;

		public override void Copy(Entity entity)
		{
			base.Copy(entity);

			Permission source = entity as Permission;

			if (source == null)
				throw new ArgumentException("entity", "entity must be an instance of Permission.");

			Description = source._description;
			RoleId = source._roleId;
		}
	}
}
