//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace Freedom.Domain.Model
{
	public static class Tables
	{
		public static IEnumerable<string> SyncOrder
		{
			get
			{
				yield return "User";
				yield return "WatchList";
				yield return "ApplicationSetting";
				yield return "MarketIndex";
				yield return "Role";
				yield return "StockExchange";
				yield return "Strategy";
				yield return "UserRole";
				yield return "Stock";
				yield return "WatchListStock";
			}
		}
	}
}
