//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics;
using System.Globalization;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using Freedom.Domain.Infrastructure;
using Freedom.Domain.Services.Repository;
using Freedom.Collections;
using Freedom.ComponentModel;

namespace Freedom.Domain.Model
{
	[DataContract(Namespace = Namespace)]

	public partial class WatchListStock : Entity
	{
		public WatchListStock()
		{
		}

		public WatchListStock(Guid watchListId, Guid stockId)
			: this()
		{
			_watchListId = watchListId;
			_stockId = stockId;
		}

		public override string EntityTypeName
		{
			get { return "WatchListStock"; }
		}

		[DataMember(EmitDefaultValue = false)]
		public Guid WatchListId
		{
			get { return _watchListId; }
			set { _watchListId = value; }
		}
		private Guid _watchListId;

		[DataMember(EmitDefaultValue = false)]
		public Guid StockId
		{
			get { return _stockId; }
			set { _stockId = value; }
		}
		private Guid _stockId;

		[DataMember(EmitDefaultValue = false)]
		public virtual WatchList WatchList
		{
			get { return _watchList; }
			set
			{
				if (object.ReferenceEquals(_watchList, value)) return;

				_watchList = value;

				if (value != null)
					WatchListId = value.Id;
			}
		}
		private WatchList _watchList;

		[DataMember(EmitDefaultValue = false)]
		public virtual Stock Stock
		{
			get { return _stock; }
			set
			{
				if (object.ReferenceEquals(_stock, value)) return;

				_stock = value;

				if (value != null)
					StockId = value.Id;
			}
		}
		private Stock _stock;

		public virtual void Copy(Entity entity)
		{
			WatchListStock source = entity as WatchListStock;

			if (source == null)
				throw new ArgumentException("entity", "entity must be an instance of WatchListStock.");

			WatchListId = source._watchListId;
			StockId = source._stockId;
		}
	}
}
